// plugin reference
// https://docs.gradle.org/current/userguide/groovy_plugin.html

plugins {
    id 'groovy'
}

group = 'my.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Groovy API Reference and document
    // https://docs.groovy-lang.org/docs/groovy-3.0.22/html/gapi/
    // https://docs.groovy-lang.org/docs/groovy-3.0.22/html/documentation/
    implementation 'org.codehaus.groovy:groovy-all:3.0.22'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // EclipseLink (JPA impl)
    implementation 'org.eclipse.persistence:eclipselink:4.0.6'
    runtimeOnly 'com.mysql:mysql-connector-j:9.3.0'
}

// NOTE: If you don't need to run the tests, please uncomment the following line.
// project.gradle.startParameter.excludedTaskNames.add("test")

test {
    useJUnitPlatform()
}
