// plugin reference
// https://docs.gradle.org/current/userguide/groovy_plugin.html

plugins {
    id 'groovy'
}

group = 'my.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Groovy API Reference and document
    // https://docs.groovy-lang.org/docs/groovy-5.0.5/html/gapi/
    // https://docs.groovy-lang.org/docs/groovy-5.0.5/html/documentation/
    implementation 'org.apache.groovy:groovy-all:5.0.5'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

// NOTE: If you don't need to run the tests, please uncomment the following line.
// project.gradle.startParameter.excludedTaskNames.add("test")

test {
    useJUnitPlatform()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
