// plugin reference
// https://docs.gradle.org/current/userguide/groovy_plugin.html

plugins {
    id 'groovy'
}

group = 'my.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Groovy API Reference and document
    // https://docs.groovy-lang.org/docs/groovy-3.0.22/html/gapi/
    // https://docs.groovy-lang.org/docs/groovy-3.0.22/html/documentation/
    implementation 'org.codehaus.groovy:groovy-all:3.0.22'
    testImplementation platform('org.junit:junit-bom:5.10.0')

    implementation 'org.bouncycastle:bcprov-jdk18on:1.77'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.77'
    implementation 'com.google.crypto.tink:tink:1.12.0'

    testImplementation 'org.junit.jupiter:junit-jupiter'
}

// NOTE: If you don't need to run the tests, please uncomment the following line.
// project.gradle.startParameter.excludedTaskNames.add("test")

test {
    useJUnitPlatform()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
